### ISSUE TITLE
Multiple values?

### ISSUE THREAD

**Issue by greghendershott** [jackfirth/racket-mock#1]
This package looks great!

One question: Should this handle functions that return multiple values?

For example:

1) Change `mock-calls` to have a `results`, plural, `list` member:

```
[struct mock-call ([args list?] [results list?])]
...
(struct mock-call (args results) #:prefab)
```

2) Change `wrapper` in `make-mock` to use `call-with-values`:

```
(define (wrapper proc . vs)
  (define results (call-with-values (λ () (apply proc vs))
                                    list))
  (add-call! (mock-call vs results))
  results)
```

Unfortunately that wouldn't be backward-compatible, what with the `result` `any/c` member becoming `results` `list?`. Which is why I didn't submit a PR. (Also I don't have an immediate need for this, yet. It's only my comment from checking out the code.)

But you're at version 0.1 and it's brand new so maybe it would be OK to be backward-incompatible?

**Comment by jackfirth** [comment]
Backwards incompatible changes are definitely okay right now, both because of the 0.1 version and because I've namespaced the package as `jack-mock` on the catalog to imply it's not meant for more than personal use at the moment. Multi-value mocks are definitely a good idea, a PR would be most welcome.
