### ISSUE TITLE
Arguments: Support for Currying

### ISSUE THREAD

**Issue by countvajhula** [jackfirth/racket-mock#134]
Hi there,
The arguments package is really neat! How come it's provided as part of `racket-mock` and not as its own package?

I've been using this package to represent arguments passed to a function, but have run into an issue when using it with curried functions. The issue at a high level is that positional arguments form a list for a fully qualified function, but for curried functions, I believe we can't represent positional arguments as a single list, since arguments may be supplied on either side of this list (by left- and right-currying) at any time prior to the point when the function is actually evaluated. It could make sense to represent positional arguments as a pair of lists internally.

Example:

```
((curryr (curry string-append "1") "2") "3") ;=> "132"
```
The argument list for the curried function at the intermediate stage is something like `'("1" _ "2")` (note the two currying directions). Treating it as simply `'("1" "2")` would lead to incorrect behavior when the outermost call happens, since we'd either compose the arguments as `'("3" "1" "2")` or as `'("1" "2" "3")` depending on the order in which we merge the arguments, neither of which is the expected list of arguments, `'("1" "3" "2")`. So we don't have a way of representing the arguments of this function using the arguments structure in its current form.

One way to address this could be to represent the positional arguments internally as a pair of lists, `left-args` and `right-args`, and the current `arguments-positional` could be retained as a function that internally `appends` the two sublists together. And existing behavior could probably be preserved by just using the `left` list.

In this representation, the above example would look like `left-args = '("1") right-args = '("2")`, which when called with `"3"` would become `left-args = '("1" "3") right-args = '("2")`.

For reference, [this](https://docs.racket-lang.org/relation/Functional_Primitives.html#%28def._%28%28lib._relation%2Ffunction..rkt%29._function%29%29) is the struct I'm using arguments with, where it was formerly used to represent the arguments passed to a function as an `args` attribute. I changed that to explicitly represent `left`, `right`, and `keyword` args as attributes when I discovered the issue with currying. It would be ideal if the struct could abstract the makeup of the arguments behind the arguments structure.

**Comment by jackfirth** [comment]
Hi! Interesting idea, I can see where you're coming from. Also thanks for your interest in the package!

Quick note: the arguments stuff is provided from [its own package](https://pkgs.racket-lang.org/package/arguments), but it _used_ to be built-in to the mock package. For backwards compatibility, the mock package re-exports the arguments code so that any code that relied on that won't break. New code should install the `arguments` and `mock` packages separately rather than relying on just the `mock` package.

For currying: I personally don't actually like currying. I vastly prefer the [`fancy-app`](https://docs.racket-lang.org/fancy-app/) approach where instead of functions being implicitly curried, a hole marker (`_`) is used. Your `(curryr (curry string-append "1") "2")` example would be `(string-append "1" _ "2")` in `fancy-app` notation. This means partially applied arguments can be interspersed arbitrarily, so if you want to represent that you'd need something that can handle a call like `(string-append "1" _ "2" _ "3")`.

More broadly though, I think it would be better to express partial application as a separate concept _on top_ of the `arguments` struct, not _within_ it. An `arguments` instance represents the arguments to a single function call. Partial application is inherently about _multiple_ function calls. Maybe a good way to represent that would be some sort of sparse list for the positional arguments, or a list of [option values](https://docs.racket-lang.org/rebellion/Option_Values.html) where `absent` represents a hole for a curried argument. So something like this:

```scheme
(define args (partial-arguments "1" _ "2" _ "3"))
(define f (partial-arguments-apply args string-append))

> (partial-arguments-positional args)
(list (present "1") #<absent> (present "2") #<absent> (present "3"))
> (f "a" "b")
"1a2b3"
```

What do you think?

**Comment by countvajhula** [comment]
I see, yeah being able to specify arbitrary locations for each argument seems to be general way to address this, which as a particular instance would address the case of currying. Although with a curried function, since we're building up the arguments incrementally, we could still achieve any ordering of arguments using only left and right lists. So `(string-append "1" _ "2" _ "3")` could look something like `(string-append "1" - "3")` and then building up on either side until we want to place the `"2"`, so in terms of generality it should be the same as `fancy-app`, for what it's worth.

The distinction you're drawing between single and multiple application makes sense, and consequently treating partial application as a higher level conception defined on top of individual arguments structs has the air of the right solution about it.

I'm not clear at the moment on what your example implies for how partial argument composition would work, i.e. `arguments-merge`, or the relationship between `partial-arguments-apply` (or is it `apply/partial-arguments`?) and `apply/arguments`. For instance, I think in modeling curried functions I'd probably want to use partial-arguments exclusively without going down to the arguments level. Would that be possible?

**Comment by countvajhula** [comment]
@jackfirth Just an update here - I added support for various "application schemes" including currying and template-based application (like fancy-app) to the [`relation/function` module](https://docs.racket-lang.org/relation/Functional_Primitives.html#%28part._.Function_.Application%29). Do you think modeling of function application schemes would be a good fit to include in the arguments library? If so, I could start a PR extracting what I have in relation/function and we could correspond on it over time and see if we can settle on an implementation that makes sense for `arguments`. Otherwise, feel free to close this issue.

Btw, I ended up using optional values to implement template-based application as you suggested. I used the data/maybe implementation since the relation package already relies on the interfaces in functional-lib, but we could use the rebellion version if we include this in the arguments library, for similar reasons. Not sure if there are other reasons to favor one or the other implementation, I didn't see any comparisons in the docs.

**Comment by jackfirth** [comment]
I think they make sense as a separate module. The `arguments` module deals with just that: collections of arguments. More complex representations of function application ought to be in a separate module, and I think it makes sense for you to own that module in your own package. You're the expert on the implementation and its use cases, after all.

As for whether to use `rebellion/base/option` or `data/maybe`, I think go with `data/maybe` since you're already relying on `functional-lib`. Seems less complicated that way. They're pretty much equivalent anyway.

I'm going to close this issue for now. Thank you for implementing this and writing docs for it in `relation/function` though, it's a really interesting read and I like seeing the design space explored.

**Comment by countvajhula** [comment]
Cool, you got it, and I appreciate the discussion 👍  💯  😸
