### ISSUE TITLE
Check failure

### ISSUE THREAD

**Issue by vdloo** [jackfirth/racket-mock#18]
Hi,

I'm trying to write a rackunit test as explained in the docs [here](https://docs.racket-lang.org/mock/index.html#%28def._%28%28lib._mock%2Fmain..rkt%29._check-mock-called-with~3f%29%29) but I can't get it to work and there is no other code on github that seems to be using `check-mock-called-with?` where I can draw inspiration from so I figured I'd open an issue here. 

I have a sourcefile like this:

```
#!/usr/bin/env racket
#lang racket/base

(provide a-function-i-want-to-test)

(define (a-function-i-want-to-test a) 1)
```

And a testfile that looks like this:

```
(require mock)
(require "../sourcefile.rkt")

(define main-tests
  (test-suite
    "My example test"

    (test-case
      "test that my function is called with the right argument"
      (let ([mock-function-i-want-to-test (make-mock a-function-i-want-to-test)]
            [return (a-function-i-want-to-test 1)])
        (check-mock-called-with? '(1) mock-function-i-want-to-test)))))
```

When I run the test it fails with:

```
My example test > test that my function is called with the right argument
test that my function is called with the right argument
FAILURE
name:       check-mock-called-with?
location:   /home/vdloo/.racket/6.4/pkgs/jack-mock/mock/private/check.rkt:10:4
params:     '(1)
#<procedure:...t/private/kw.rkt:213:14>
Check failure
--------------------
0 success(es) 1 failure(s) 0 error(s) 1 test(s) run
```

Can you tell me what I'm doing wrong? Does this perhaps have to do with https://github.com/jackfirth/racket-mock/issues/17?

**Comment by jackfirth** [comment]
Mocks in this library don't mutate the original procedure, unlike some mocking libraries in other languages. To test behavior with mocks, you have to call the mocks themselves rather than the procedures being mocked:

``` racket
(test-suite "My example test"
  (test-case "test that my function is called with the right argument"
    (let ([mock-function-i-want-to-test (make-mock a-function-i-want-to-test)]
          [return (mock-function-i-want-to-test 1)]) ; notice we're calling the mock
      (check-mock-called-with? '(1) mock-function-i-want-to-test))))
```

This is unrelated to #17, but it is why `define/mock` exists. If you want your function to call real implementations normally but call mocks in test, using `define/mock` creates two definitions of your function via macros. In addition to the normal implementation, in a test submodule it defines an implementation that calls the mocks.

**Comment by vdloo** [comment]
Oh right, I get it now. That's actually pretty clever. Thanks a lot!

**Comment by jackfirth** [comment]
No problem, glad I could help :smile:
